from __future__ import annotations

from pathlib import Path

import cv2
import numpy as np
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.ttLib import TTFont


def char_to_glyph_name(font: TTFont, ch: str) -> str | None:
    codepoint = ord(ch)
    for table in font["cmap"].tables:
        if codepoint in table.cmap:
            return table.cmap[codepoint]
    return None


def _glyph_bbox(font: TTFont, glyph_name: str) -> tuple[int, int, int, int] | None:
    glyph = font["glyf"][glyph_name]
    glyph.recalcBounds(font["glyf"])
    if not hasattr(glyph, "xMin") or glyph.xMax <= glyph.xMin or glyph.yMax <= glyph.yMin:
        return None
    return int(glyph.xMin), int(glyph.yMin), int(glyph.xMax), int(glyph.yMax)


def _signed_area(points: list[tuple[int, int]]) -> float:
    area = 0.0
    for (x1, y1), (x2, y2) in zip(points, points[1:] + points[:1]):
        area += x1 * y2 - x2 * y1
    return area / 2.0


def _contour_level(idx: int, hierarchy: np.ndarray) -> int:
    level = 0
    parent = int(hierarchy[idx][3])
    while parent != -1:
        level += 1
        parent = int(hierarchy[parent][3])
    return level


def _contour_to_units(
    contour: np.ndarray,
    image_shape: tuple[int, int],
    bbox: tuple[int, int, int, int],
) -> list[tuple[int, int]]:
    h, w = image_shape
    x_min, y_min, x_max, y_max = bbox
    points: list[tuple[int, int]] = []
    for x, y in contour:
        x_unit = x_min + (float(x) / max(1.0, float(w - 1))) * (x_max - x_min)
        y_unit = y_max - (float(y) / max(1.0, float(h - 1))) * (y_max - y_min)
        points.append((int(round(x_unit)), int(round(y_unit))))
    return points


def glyph_from_bitmap(font: TTFont, glyph_name: str, bitmap: np.ndarray):
    if "glyf" not in font:
        raise ValueError("Only TrueType glyf fonts are supported for TTF batch generation")
    bbox = _glyph_bbox(font, glyph_name)
    if bbox is None:
        return None
    binary = (np.clip(bitmap, 0.0, 1.0) > 0.18).astype(np.uint8) * 255
    contours, hierarchy = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    if hierarchy is None or len(contours) == 0:
        return None

    hierarchy = hierarchy[0]
    levels = {idx: _contour_level(idx, hierarchy) for idx in range(len(contours))}
    order = sorted(range(len(contours)), key=lambda idx: (levels[idx], -cv2.contourArea(contours[idx])))
    pen = TTGlyphPen(font.getGlyphSet())
    made = 0
    for idx in order:
        contour = contours[idx]
        if cv2.contourArea(contour) < 1.2:
            continue
        epsilon = max(0.35, 0.002 * cv2.arcLength(contour, True))
        approx = cv2.approxPolyDP(contour, epsilon, True)[:, 0, :].astype(np.float32)
        if len(approx) < 3:
            continue
        points = _contour_to_units(approx, bitmap.shape, bbox)
        if len(set(points)) < 3:
            continue
        target_sign = 1 if levels[idx] % 2 == 0 else -1
        if _signed_area(points) * target_sign < 0:
            points = list(reversed(points))
        pen.moveTo(points[0])
        for point in points[1:]:
            pen.lineTo(point)
        pen.closePath()
        made += 1
    if made == 0:
        return None
    glyph = pen.glyph()
    glyph.recalcBounds(font["glyf"])
    return glyph


def set_generated_names(font: TTFont, family: str, postscript: str | None = None) -> None:
    subfamily = "Regular"
    full = f"{family} {subfamily}"
    postscript_name = postscript or "".join(ch for ch in full if ch.isalnum()) + "-Regular"
    values = {
        1: family,
        2: subfamily,
        3: f"{full}; generated by eco-font",
        4: full,
        5: "Version 1.000; generated by eco-font",
        6: postscript_name,
        8: "eco-font lab",
        9: "eco-font lab",
        16: family,
        17: subfamily,
    }
    name_table = font["name"]
    name_table.names = [name for name in name_table.names if name.nameID not in set(values) | {18, 21, 22}]
    for name_id, value in values.items():
        name_table.setName(value, name_id, 3, 1, 0x409)
        name_table.setName(value, name_id, 3, 1, 0x412)
        name_table.setName(value, name_id, 1, 0, 0)


def export_ttf_from_bitmaps(
    source_font: str | Path,
    char_to_bitmap: dict[str, np.ndarray],
    output_font: str | Path,
    family_name: str,
    postscript_name: str | None = None,
) -> tuple[Path, int, list[str]]:
    output = Path(output_font)
    output.parent.mkdir(parents=True, exist_ok=True)
    font = TTFont(str(source_font))
    if "glyf" not in font:
        raise ValueError("Only TrueType glyf fonts are supported for TTF batch generation")

    replaced = 0
    skipped: list[str] = []
    for ch, bitmap in char_to_bitmap.items():
        glyph_name = char_to_glyph_name(font, ch)
        if glyph_name is None or glyph_name not in font["glyf"]:
            skipped.append(ch)
            continue
        glyph = glyph_from_bitmap(font, glyph_name, bitmap)
        if glyph is None:
            skipped.append(ch)
            continue
        font["glyf"][glyph_name] = glyph
        replaced += 1

    if replaced == 0:
        raise ValueError("No glyphs were replaced")
    for tag in ["TSI0", "TSI1", "TSI2", "TSI3", "TSI5"]:
        if tag in font:
            del font[tag]
    set_generated_names(font, family_name, postscript_name)
    font.save(str(output))
    return output, replaced, skipped

